In [ ]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download("vader_lexicon")
import pandas as pd
data = pd.read_csv("/content/data0.31.csv")
data = data.dropna()
print(data.head())

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

                                          text kotor  likeCount  \
0                       @detikcom Vincent &gt; Desta          0
1                                   Vincent&gt;Desta          0
2  Hai berhubung gw fans berat vincent desta dan ...          0
3  Tiket 200k dapet kaos,totebag,bunga mawar fres...          1
4  @EIGHT1NY iya si betul tp ak ngeliatnya emang ...          0

                                                Teks
0                                   vincent gt desta
1                                   vincent gt desta
2  hai berhubung gw fans berat vincent desta dan ...
3  tiket k dapet kaos totebag bunga mawar fresh p...
4  iya si betul tp ak ngeliatnya emang pure berca...

In [ ]:
sentiments = SentimentIntensityAnalyzer()
data["Yes"] = [sentiments.polarity_scores(i)["neg"] for i in data["Teks"]]
data["No"] = [sentiments.polarity_scores(i)["pos"] for i in data["Teks"]]
data["Compound"] = [sentiments.polarity_scores(i)["compound"] for i in data["Teks"]]

data.head()

,text kotor,likeCount,Teks,Yes,No,Compound
0,@detikcom Vincent &gt; Desta,0,vincent gt desta,0.0,0.512,0.2732
1,Vincent&gt;Desta,0,vincent gt desta,0.0,0.512,0.2732
2,Hai berhubung gw fans berat vincent desta dan ...,0,hai berhubung gw fans berat vincent desta dan ...,0.0,0.000,0.0000
3,"Tiket 200k dapet kaos,totebag,bunga mawar fres...",1,tiket k dapet kaos totebag bunga mawar fresh p...,0.0,0.049,0.3182
4,@EIGHT1NY iya si betul tp ak ngeliatnya emang ...,0,iya si betul tp ak ngeliatnya emang pure berca...,0.0,0.000,0.0000

In [ ]:
data

,text kotor,likeCount,Teks,Yes,No,Compound
0,@detikcom Vincent &gt; Desta,0,vincent gt desta,0.0,0.512,0.2732
1,Vincent&gt;Desta,0,vincent gt desta,0.0,0.512,0.2732
2,Hai berhubung gw fans berat vincent desta dan ...,0,hai berhubung gw fans berat vincent desta dan ...,0.0,0.000,0.0000
3,"Tiket 200k dapet kaos,totebag,bunga mawar fres...",1,tiket k dapet kaos totebag bunga mawar fresh p...,0.0,0.049,0.3182
4,@EIGHT1NY iya si betul tp ak ngeliatnya emang ...,0,iya si betul tp ak ngeliatnya emang pure berca...,0.0,0.000,0.0000
...,...,...,...,...,...,...
395,Apakah ini efek nonton vincent desta di segala...,0,apakah ini efek nonton vincent desta di segala...,0.0,0.000,0.0000
396,Nulis Lagu Senja Bisa Ketemu Vincent Destaâ¼ï...,1,nulis lagu senja bisa ketemu vincent desta,0.0,0.000,0.0000
397,@denny_trizki @kisahtanahjawa @NETtv_Channel G...,0,trizki channel gak mungkin bro sekelas net tv ...,0.0,0.000,0.0000
398,vincent desta,1,vincent desta,0.0,0.000,0.0000
399,@starfess jongu tuh mood btt anaknya jd biar r...,5,jongu tuh mood btt anaknya jd biar rame aja gi...,0.0,0.109,0.2960

In [ ]:
score = data["Compound"].values
sentiment = []
for i in score:
  if i >= 0.00 :
    sentiment.append('No')
  else:
      sentiment.append('Yes')
data["label"] = sentiment
data

,text kotor,likeCount,Teks,Yes,No,Compound,label
0,@detikcom Vincent &gt; Desta,0,vincent gt desta,0.0,0.512,0.2732,No
1,Vincent&gt;Desta,0,vincent gt desta,0.0,0.512,0.2732,No
2,Hai berhubung gw fans berat vincent desta dan ...,0,hai berhubung gw fans berat vincent desta dan ...,0.0,0.000,0.0000,No
3,"Tiket 200k dapet kaos,totebag,bunga mawar fres...",1,tiket k dapet kaos totebag bunga mawar fresh p...,0.0,0.049,0.3182,No
4,@EIGHT1NY iya si betul tp ak ngeliatnya emang ...,0,iya si betul tp ak ngeliatnya emang pure berca...,0.0,0.000,0.0000,No
...,...,...,...,...,...,...,...
395,Apakah ini efek nonton vincent desta di segala...,0,apakah ini efek nonton vincent desta di segala...,0.0,0.000,0.0000,No
396,Nulis Lagu Senja Bisa Ketemu Vincent Destaâ¼ï...,1,nulis lagu senja bisa ketemu vincent desta,0.0,0.000,0.0000,No
397,@denny_trizki @kisahtanahjawa @NETtv_Channel G...,0,trizki channel gak mungkin bro sekelas net tv ...,0.0,0.000,0.0000,No
398,vincent desta,1,vincent desta,0.0,0.000,0.0000,No
399,@starfess jongu tuh mood btt anaknya jd biar r...,5,jongu tuh mood btt anaknya jd biar rame aja gi...,0.0,0.109,0.2960,No

In [ ]:
data.to_excel('data0.32.xlsx', index = False)